### ISSUE TITLE
When configuring the App, it updates all the Domoticz switch notification settings

### ISSUE THREAD

**Issue by gcaley** [verbem/Domoticz-Server#1]
When i install and configure the Domoticz-Server app, and tell it to update Domoticz with certain Smartthings devices, it also updates all my Domoticz switches with notification settings. I've had to go through and remove them all..

Domoticz v3.902
SmartThings Domoticx-Server app v7.03

**Comment by verbem** [comment]
Not good. Do you have also switches  selected from domoticz into st in the
app?

met vriendelijke groeten,

Martin

Op vr 13 apr. 2018 14:54 schreef gcaley <notifications@github.com>:

**Comment by gcaley** [comment]
I should add it didn't just add notifications to the switches, but most of my other devices too. It didn't add to all though, just certain types.

**Comment by verbem** [comment]
It should not touch devices that are not in st will look into it.

met vriendelijke groeten,

Martin

Op vr 13 apr. 2018 15:07 schreef gcaley <notifications@github.com<mailto:notifications@github.com>>:

I should add it didn't just add notifications to the switches, but most of my other devices too. It didn't add to all though, just certain types.

**Comment by gcaley** [comment]
so I can roughly see what is intended, and that is that devices imported into ST then have a Domoticz notification added, so as to update a change in value. It didn't automatically add the custom HTTP URL in DM, but I've added that now. It might be this is the behaviour planned. The notifications where added to the devices imported into ST.

I did notice that if I already had a notification in DM, then the app doesn't add its own notifications, which it should I would guess?

I also noted that when the APP added an ST motion sensor, it appeared in incorrectly in DM as a temperature device

**Comment by gcaley** [comment]
Great app by the way, it's saved me a lot of ST pain, as in understand DM well, but not ST!

**Comment by verbem** [comment]
I will not add http action url automatically. I played with it. But getting weird results.

It looks if notifications are defined. If it is it will not touch those. But if you clear them in dm it will add them.

met vriendelijke groeten,

Martin


Op vr 13 apr. 2018 15:31 schreef gcaley <notifications@github.com<mailto:notifications@github.com>>:

Great app by the way, it's saved me a lot of ST pain, as in understand DM well, but not ST!

**Comment by verbem** [comment]
Wrt the motion sensor.. does it have a temp component as well in st?

met vriendelijke groeten,

Martin

Op vr 13 apr. 2018 16:44 schreef Martin Verbeek <verbeek_martin@hotmail.com<mailto:verbeek_martin@hotmail.com>>:
I will not add http action url automatically. I played with it. But getting weird results.

It looks if notifications are defined. If it is it will not touch those. But if you clear them in dm it will add them.

met vriendelijke groeten,

Martin


Op vr 13 apr. 2018 15:31 schreef gcaley <notifications@github.com<mailto:notifications@github.com>>:

Great app by the way, it's saved me a lot of ST pain, as in understand DM well, but not ST!

**Comment by gcaley** [comment]
I think the notifications are working now. I'll close this and open a separate Issue for the problem with the Motion Sensor

**Comment by gcaley** [comment]
Or I won't. In investigating I realised it was because the ST device is a multi-function device, and had created three DM devices... All ok now!
