### ISSUE TITLE
domoticzOnOff in namespace 'verbem' not found

### ISSUE THREAD

**Issue by spartan1017** [verbem/Domoticz-Server#2]
Seems with my installation we're struggling with the latest version to create the actual device in ST.

The following error message is being returned, happy to pass full logs if it helps. 

22:02:11: error [defineDomoticzInSmartThings] Cannot create child device. null Error: physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'domoticzOnOff' in namespace 'verbem' not found.

**Comment by verbem** [comment]
You have the device type handlers installed from the same repo you got the
app from?

Op do 27 dec. 2018 23:06 schreef spartan1017 <notifications@github.com:

**Comment by spartan1017** [comment]
Is there anything specific I can do to check? pulling verbem/Domoticz-Server should in theory pull down all artifacts? but I can only see the groovy script in the IDE

**Comment by spartan1017** [comment]
User error! Thanks :)
