### ISSUE TITLE
Smartthings and Domoticz

### ISSUE THREAD

**Issue by salopette** [verbem/Domoticz-Server#6]
Do you need a Smartthings HUB for this, or is the app and domoticz server sufficient?

Is there an installation guide?

**Comment by verbem** [comment]
You need the hub

Op 24 okt. 2019 19:49 schreef salopette <notifications@github.com>:

Do you need a Smartthings HUB for this, or is the app and domoticz server sufficient?

Is there an installation guide?

**Comment by salopette** [comment]
THX!
